### ISSUE TITLE
Problem in test specs

### ISSUE THREAD

**Issue by georgejeffery** [learn-co-curriculum/sinatra-mvc-lab#28]
Think eamStray should be ayStream according to individual word tests

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙

**Comment by Awilmerding1** [comment]
I believe this part of the test actually needs to be changed back. In the individual test the example is:
expect(words.piglatinize("spray")).to eq("ayspray") which begins with "ay" because that is at the end of the word "spray". 

For "Stream" the piglatinized version should be "eamStray" since consonant clusters are all moved to the end.
